// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_RHOeRJy7GCdes7crWWCtUkgdE0n1Au4',
    appId: '1:768307294199:web:d4c636d6287a7030e4c8f2',
    messagingSenderId: '768307294199',
    projectId: 'stackbudget-2025',
    authDomain: 'stackbudget-2025.firebaseapp.com',
    storageBucket: 'stackbudget-2025.firebasestorage.app',
    measurementId: 'G-F0LFV5DJ67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj3ehJ5JbM3gkxvfd34EqGURW6nx6SBBA',
    appId: '1:768307294199:android:91ee5d3f18c8e1d1e4c8f2',
    messagingSenderId: '768307294199',
    projectId: 'stackbudget-2025',
    storageBucket: 'stackbudget-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBiK01GyJaA2hXdBeiSL5TTAwGquAD0E4',
    appId: '1:768307294199:ios:738913d0ec755135e4c8f2',
    messagingSenderId: '768307294199',
    projectId: 'stackbudget-2025',
    storageBucket: 'stackbudget-2025.firebasestorage.app',
    iosBundleId: 'com.eduardoazevedo.stackbudget',
  );
}
